name: Docs release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_USER_PAT }}
          show-progress: false
      - name: Build and push docker image
        run: |
          echo "${{ secrets.QUAY_PASSWORD }}" | docker login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin
          
          docker buildx create --use
          docker buildx build --push --file docker/Dockerfile --tag quay.io/simplecontainer/docs:${{ github.ref_name }} .

  release:
    runs-on: ubuntu-latest
    needs: [ dockerize ]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_USER_PAT }}
          show-progress: false
      - name: Git kungfu
        run: |
          git tag -d ${{ github.ref_name }}
          git push --delete origin ${{ github.ref_name }}

          # Update version to match tag version, git push in next step
          echo ${{ github.ref_name }} > version
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated version tracking [no ci]

          branch: main
          file_pattern: 'version'
          repository: .
          tagging_message: '${{ github.ref_name }}'
          push_options: '--force'

          commit_user_name: bot
          commit_user_email: bot@qdnqn.org
          commit_author: Author <actions@github.com>
      - uses: ncipollo/release-action@v1
        with:
          body: "Automatically created - fill in accordingly"
          allowUpdates: true
          draft: false
          tag: ${{ github.ref_name }}
